/**
 * Translation dictionaries for Seed Alias
 * Supports English (en-US) and Brazilian Portuguese (pt-BR)
 */

const translations = {
  'en-US': {
    app: {
      title: 'SEED ALIAS',
      tagline: 'Cryptographic Seed Protection',
      offlineMode: 'Offline Mode',
      onlineMode: 'Online (Warning)',
      offlineTooltip: 'For maximum security, work offline to protect against network-based threats like keyloggers and remote attackers',
      version: 'v1.2.0'
    },
    security: {
      warningTitle: 'Security Notice',
      warningText: 'Never share your passphrase or encrypted seed with anyone. Store securely offline. All operations are performed locally in your browser.',
      dismissAria: 'Dismiss warning'
    },
    nav: {
      descriptionTitle: 'Description & Instructions'
    },
    encrypt: {
      title: 'Encrypt',
      passphraseLabel: 'Passphrase',
      passphrasePlaceholder: 'Enter your memorable passphrase',
      seedLabel: 'Seed to encrypt',
      seedPlaceholder: 'Enter your seed words',
      button: 'Encrypt',
      saveButton: 'Save',
      statusWaiting: 'Waiting',
      statusSuccess: 'Encrypted',
      statusError: 'Error',
      algorithm: 'AES-256-GCM',
      resultLabel: 'Encrypted seed:'
    },
    decrypt: {
      title: 'Decrypt',
      encryptedLabel: 'Encrypted seed',
      encryptedPlaceholder: 'Paste encrypted seed here',
      passphraseLabel: 'Passphrase',
      passphrasePlaceholder: 'Enter your passphrase',
      button: 'Decrypt',
      saveButton: 'Save',
      statusWaiting: 'Waiting',
      statusSuccess: 'Decrypted',
      statusError: 'Error',
      algorithm: 'AES-256-GCM',
      resultLabel: 'Decrypted seed:'
    },
    scramble: {
      optionLabel: 'Scramble for extra protection',
      codeLabel: 'Scramble code',
      codePlaceholder: 'e.g., 01020304',
      button: 'Scramble',
      saveButton: 'Save',
      statusWaiting: 'Waiting',
      statusSuccess: 'Scrambled',
      statusError: 'Error',
      algorithm: 'Byte Swap',
      resultLabel: 'Scrambled encrypted seed:'
    },
    unscramble: {
      optionLabel: 'Unscramble first',
      scrambledLabel: 'Scrambled encrypted seed',
      scrambledPlaceholder: 'Paste scrambled seed here',
      codeLabel: 'Unscramble Code',
      codePlaceholder: 'e.g., 01020304',
      button: 'Unscramble',
      statusWaiting: 'Waiting',
      statusSuccess: 'Unscrambled',
      statusError: 'Error',
      resultLabel: 'Unscrambled encrypted seed:'
    },
    common: {
      copyTooltip: 'Copy to clipboard',
      loading: 'Loading...',
      or: 'Or',
      loadFromFile: 'load from file:',
      browse: 'Browse',
      copied: 'Copied!',
      save: 'Saving...',
      saved: 'Saved!'
    },
    instructions: {
      paragraph1: 'Use this web page to create an alias for your seed. Define a passphrase which you are familiar and can always remember. The passphrase will be used to encrypt and decrypt your seed. Optionally, you can scramble your encrypted seed to get higher protection.',
      paragraph2: 'After seed encryption, you should save the encrypted seed to a file and store in a secured environment. Never store it online or send it over wire.',
      paragraph3: 'If you are planning save it online or send it over wire, it is recommend that you scramble it first before saving it to a file. Scramble your encrypted seed providing a pair of bytes position for the byte swap operation. After scramble your encrypted seed and save it to a file you may compress it with a password generating a binary file, achieving higher protection.',
      paragraph4: 'Example of scramble codes:',
      example1: '0102, will swap the bytes at position 1 and 2, i.e., will swap the first by the second byte',
      example2: '2107, will swap the bytes at positions 21 and 7',
      example3: '21071312, will swap the bytes at positions 21 and 7. And after will swap bytes at positions 13 and 12',
      obs1: 'OBS: Positions are not zero based like array index. They are one (1) based.',
      obs2: 'OBS: You can provide as many position pairs as you want.',
      obs3: 'OBS: Position value less than 10 must be prefixed with digit zero (0). Ex: 09.',
      obs4: 'OBS: Positions must not be greater than encrypted seed bytes length.',
      obs5: 'OBS: You should keep the passphrase secret, it\'s recommended that you do not write it down. It should be a sentence that you will never forget, so keep in your mind.',
      dangerWarning: 'If you share the information generated by this page with anyone, they can steal your assets. Anyone asking you to share your secret passphrase or your seed is a scammer. Do NOT copy & paste information from this page or send it to anyone offering to help you on Twitter, Discord, Telegram, Etherscan, or Line. They will steal your coins.'
    },
    validation: {
      weakPassphrase: 'Weak passphrase - add more characters',
      fairPassphrase: 'Fair passphrase - could be stronger',
      goodPassphrase: 'Good passphrase',
      strongPassphrase: 'Strong passphrase',
      invalidScrambleCode: 'Invalid scramble code format. Use pairs like 0102, 2107',
      invalidSeed: 'Please enter a seed to encrypt'
    }
  },
  'pt-BR': {
    app: {
      title: 'SEED ALIAS',
      tagline: 'Proteção Criptográfica de Seed',
      offlineMode: 'Modo Offline',
      onlineMode: 'Online (Atenção)',
      offlineTooltip: 'Para máxima segurança, trabalhe offline para se proteger contra ameaças de rede como keyloggers e atacantes remotos',
      version: 'v1.2.0'
    },
    security: {
      warningTitle: 'Aviso de Segurança',
      warningText: 'Nunca compartilhe sua senha ou seed criptografado com ninguém. Armazene de forma segura offline. Todas as operações são realizadas localmente no seu navegador.',
      dismissAria: 'Dispensar aviso'
    },
    nav: {
      descriptionTitle: 'Descrição e Instruções'
    },
    encrypt: {
      title: 'Criptografar',
      passphraseLabel: 'Senha',
      passphrasePlaceholder: 'Digite sua senha memorável',
      seedLabel: 'Seed para criptografar',
      seedPlaceholder: 'Digite suas palavras seed',
      button: 'Criptografar',
      saveButton: 'Salvar',
      statusWaiting: 'Aguardando',
      statusSuccess: 'Criptografado',
      statusError: 'Erro',
      algorithm: 'AES-256-GCM',
      resultLabel: 'Seed criptografado:'
    },
    decrypt: {
      title: 'Descriptografar',
      encryptedLabel: 'Seed criptografado',
      encryptedPlaceholder: 'Cole o seed criptografado aqui',
      passphraseLabel: 'Senha',
      passphrasePlaceholder: 'Digite sua senha',
      button: 'Descriptografar',
      saveButton: 'Salvar',
      statusWaiting: 'Aguardando',
      statusSuccess: 'Descriptografado',
      statusError: 'Erro',
      algorithm: 'AES-256-GCM',
      resultLabel: 'Seed descriptografado:'
    },
    scramble: {
      optionLabel: 'Embaralhar para proteção extra',
      codeLabel: 'Código de embaralhamento',
      codePlaceholder: 'ex: 01020304',
      button: 'Embaralhar',
      saveButton: 'Salvar',
      statusWaiting: 'Aguardando',
      statusSuccess: 'Embaralhado',
      statusError: 'Erro',
      algorithm: 'Troca de Bytes',
      resultLabel: 'Seed criptografado embaralhado:'
    },
    unscramble: {
      optionLabel: 'Desembaralhar primeiro',
      scrambledLabel: 'Seed criptografado embaralhado',
      scrambledPlaceholder: 'Cole o seed embaralhado aqui',
      codeLabel: 'Código de desembaralhamento',
      codePlaceholder: 'ex: 01020304',
      button: 'Desembaralhar',
      statusWaiting: 'Aguardando',
      statusSuccess: 'Desembaralhado',
      statusError: 'Erro',
      resultLabel: 'Seed criptografado desembaralhado:'
    },
    common: {
      copyTooltip: 'Copiar para área de transferência',
      loading: 'Carregando...',
      or: 'Ou',
      loadFromFile: 'carregar do arquivo:',
      browse: 'Procurar',
      copied: 'Copiado!',
      save: 'Salvando...',
      saved: 'Salvo!'
    },
    instructions: {
      paragraph1: 'Use esta página web para criar um alias para seu seed. Defina uma senha com a qual você esteja familiarizado e sempre possa lembrar. A senha será usada para criptografar e descriptografar seu seed. Opcionalmente, você pode embaralhar seu seed criptografado para obter maior proteção.',
      paragraph2: 'Após a criptografia do seed, você deve salvar o seed criptografado em um arquivo e armazená-lo em um ambiente seguro. Nunca o armazene online ou envie pela internet.',
      paragraph3: 'Se você planeja salvá-lo online ou enviá-lo pela internet, é recomendável que você o embaralhe primeiro antes de salvá-lo em um arquivo. Embaralhe seu seed criptografado fornecendo um par de posições de bytes para a operação de troca de bytes. Após embaralhar seu seed criptografado e salvá-lo em um arquivo, você pode compactá-lo com uma senha gerando um arquivo binário, alcançando maior proteção.',
      paragraph4: 'Exemplo de códigos de embaralhamento:',
      example1: '0102, trocará os bytes nas posições 1 e 2, ou seja, trocará o primeiro pelo segundo byte',
      example2: '2107, trocará os bytes nas posições 21 e 7',
      example3: '21071312, trocará os bytes nas posições 21 e 7. E depois trocará os bytes nas posições 13 e 12',
      obs1: 'OBS: As posições não são baseadas em zero como índice de array. Elas são baseadas em um (1).',
      obs2: 'OBS: Você pode fornecer quantos pares de posições quiser.',
      obs3: 'OBS: Valor de posição menor que 10 deve ser prefixado com o dígito zero (0). Ex: 09.',
      obs4: 'OBS: As posições não devem ser maiores que o comprimento dos bytes do seed criptografado.',
      obs5: 'OBS: Você deve manter a senha em segredo, é recomendável que você não a anote. Deve ser uma frase que você nunca esquecerá, então mantenha em sua mente.',
      dangerWarning: 'Se você compartilhar as informações geradas por esta página com qualquer pessoa, eles podem roubar seus ativos. Qualquer pessoa pedindo para você compartilhar sua senha secreta ou seu seed é um golpista. NÃO copie e cole informações desta página ou as envie para ninguém oferecendo ajuda no Twitter, Discord, Telegram, Etherscan ou Line. Eles roubarão suas moedas.'
    },
    validation: {
      weakPassphrase: 'Senha fraca - adicione mais caracteres',
      fairPassphrase: 'Senha razoável - poderia ser mais forte',
      goodPassphrase: 'Boa senha',
      strongPassphrase: 'Senha forte',
      invalidScrambleCode: 'Formato de código de embaralhamento inválido. Use pares como 0102, 2107',
      invalidSeed: 'Por favor, digite um seed para criptografar'
    }
  }
};

// Make translations available globally
if (typeof window !== 'undefined') {
  window.translations = translations;
}
